### ISSUE TITLE
Switch to spdy/HTTP2

### ISSUE THREAD

**Issue by boyeborg** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-7-backend#15]
Use [spdy](https://github.com/spdy-http2/node-spdy).

Just swap the server like this:

```node
spdy
  .createServer(options, app)   // <-- Express app
  .listen(port, (err) => {
    if (err) {
      console.error(err);
    } else {
      console.log(`Listening on port: ${port}`);
    }
  });
```

**Comment by afriestad** [comment]
Hvorfor SPDY, når det er [deprecated](https://en.wikipedia.org/wiki/SPDY)? Er det ikke bedre å bruke [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2)?

**Comment by boyeborg** [comment]
Årsaken er at jeg ville ha en pakke som brukte HTTP/2 og fallback på HTTP/1. Så vidt jeg vet så har ikke andre HTTP/2-pakker jeg har funnet fallback, så da må man eventuelt lage det selv. At den også tilbyr en deprecated protokoll vil i praksis ikke ha betydning. Men jeg er enig i at det hadde vært bedre med en som tilbyr kun HTTP/2 med fallback på HTTP/1. Om du vet om en slik pakke er det bare å si i fra!

**Comment by afriestad** [comment]
Ah, I see. Jeg burde ha sett på innholdet på andre siden av den lenken; jeg trodde du tenkte å bruke SPDY-protokollen på serveren. Da er jeg i prinsippet enig i at det er best å ha en pakke med fallback til HTTP/1. Så spørs det om det egentlig er vits å ha fallback når alle som skal se siden er datastudenter og instituttansatte 🌵

**Comment by boyeborg** [comment]
ja, når du sier det er jeg enig. Vi kan godt la være å støtte HTTP/1. Egentlig er jeg ikke noe fan av all den bakoverkomapaitibeliteten uansett. Synes det er bedre å ikke støtte gammel teknologi så folk blir tvunget til å bytte. Stemmer for at vi ikke støtter HTTP/1.
HTTP/2 finnes også i [node core](https://nodejs.org/api/http2.html), men det er kun "Experimental" støtte foreløpig, så usikker på om det er bedre å bruke f.eks. [molnarg/node-http2](https://github.com/molnarg/node-http2).

Det blir uansett noe ala:
```node
import http2 from 'http2';

...

const app = express();
app.server = http2.createServer(app);

...
```

**Comment by afriestad** [comment]
Jeg ville nok gått for noe som har ordentlig støtte, ikke eksperimentell. Så sparer vi oss en del potensielt hodebry og lange netter :)
